[project]
name = "fnbsql"
version = "0.1.0"
description = "Extract transactions from an FNB account statement and store it in a sqlite database"
readme = "README.md"
authors = [
  { name = "Emilio Ziniades", email = "emilioziniades@protonmail.com" },
]
requires-python = ">=3.14"
dependencies = ["pdfplumber>=0.11.10"]

[project.scripts]
fnbsql = "fnbsql:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
